server:
  mqtt:
    host: '10.1.0.21'
    port: 1883
  zabbix:
    host: '10.1.0.10'
    port: 10051
convert:
  - topic: '/outer1/temp'
    type: 'zabbix'
    zabbix_host: 'ENVIRONMENT'
    zabbix_key: 'outside.temparature'
  - topic: '/outer1/humi'
    type: 'zabbix'
    zabbix_host: 'ENVIRONMENT'
    zabbix_key: 'outside.humidity'
  - topic: '/outer1/pres'
    type: 'zabbix'
    zabbix_host: 'ENVIRONMENT'
    zabbix_key: 'outside.pressure'
  - topic: '/test/test1'
    type: 'dump'
