server:
  mqtt:
    host: '10.1.0.21'
    port: 1883
  zabbix:
    sender: /usr/bin/zabbix_sender
    host: '10.1.0.10'
    port: 10051
convert:
  - topic: '/outer11/temp'
    type: 'zabbix'
    zabbix_host: 'ENVIRONMENT'
    zabbix_key: 'outside.temparature'
  - topic: '/outer11/humi'
    type: 'zabbix'
    zabbix_host: 'ENVIRONMENT'
    zabbix_key: 'outside.humidity'
  - topic: '/outer11/pres'
    type: 'zabbix'
    zabbix_host: 'ENVIRONMENT'
    zabbix_key: 'outside.pressure'
  - topic: '/test/test_dump'
    type: 'dump'
  - topic: '/test/test_log'
    type: 'log'
    config: './config/test_logstdout.yaml'
    logger: testlog
  - topic: '/test/test_log2'
    type: 'log'
    logger: testlog
  - topic: '/test/test_logfile'
    type: 'log'
    logger: testlogfile
    config: './config/test_logfile.yaml'

